---
title: "Sociality Simulation"
output: html_notebook
---
```{r}
library(tidyverse)
```

```{r}
#Set number of Days in a Cycle
Day <- 0; nDayCycle <- 30;
#Starting number of reproductives, workers and energy stores
nReprod <- 1; nWorker <- 0; kStore <- 0;
#Number of trips that workers and reproductives can make each day
nTripReprod <- 1; nTripWorker <- 2;
#Set amount of energy per trip that workers and reproductives make
kTripWorker <- 5; kTripReprod <- 2;
#Set amount of energy needed to create a worker and reproductive
kCreateWorker <- 2; kCreateReprod <- 10;
#Set mortality rates and rate of reprod vs. worker creation
fMortRate <- .7; birthRate <- .75;
#Set max number of reproductives and workers per day per reproductive

#Create dataframe to store data.
data <- data.frame(timestep=0,nReprod=nReprod,nWorker=nWorker,kStore=kStore)

for (i in 1:nDayCycle)
{
  #Forage as much as you can/need with workers
  #!!!!! When does Queen/reproductives stop foraging?
  #!!!!! How to incorporate mortality rate?
  
  nWorker <- (nWorker*fMortRate);
  kStore <- kStore + nWorker * nTripWorker;
  
  if(nWorker < 2)
  {
    nReprod <- (nReprod*fMortRate);
    kStore <- kStore + nReprod * nTripReprod;
  }
  
  #!!!!! How to birth the right amount? How much energy to use, save, etc.?
  while (kStore > 0)
  {
    if(kStore > kCreateReprod)
    {
      temp <- runif(1,0,1) > birthRate
      if(temp){kStore <- kStore - kCreateReprod;  nReprod <- nReprod + 1;}
      else    {kStore <- kStore - kCreateWorker;  nWorker <- nWorker + 1;}
    }
    else{
      if(kStore > kCreateWorker)
      {kStore <- kStore - kCreateWorker;  nWorker <- nWorker + 1;}
      else{break}
    }
  }
  
  #if(i%%1==0){print(paste("Day: ",i,"  kStore: ",kStore,"  nReprod: ",nReprod,"  nWorker: ",nWorker));}
  data <- rbind(data,list(i,nReprod,nWorker,kStore))
}

ggplot(data,aes(x=timestep)) + geom_line(aes(y=kStore,color="kStore")) + geom_line(aes(y=nReprod,color="nReprod")) + geom_line(aes(y=nWorker,color="nWorker")) + scale_colour_manual("",breaks = c("kStore", "nReprod", "nWorker"),values = c("kStore"="green","nReprod"="red","nWorker"="blue"))
```