---
title: "ToDo's and Progress Tracking Notebook"
output: html_notebook
---

This notebook is intended to keep track of my progress each day over intercession on this project. I'll log my TODO's each morning or night and what I've accomplished each day. Let's hope I keep up with it properly.

#Monday December 17th
###TO DO
1. Re-arrange Github repos
2. Organize Google Drive papers & PDF's
3. Print most useful papers
4. Send "progress tracking" e-mail to Seid & Graham
5. Compile genetic algorithm functions into notebook
  + Comment genetic algorithm code

###Progress
  Github repositories organized, took far longer than I thought it would. I learned he significance of .git files after attempting to create new repos out of existing but removed repo folders with .git files in them. 
  Organized Google Drive folders & papers, selected those to print.
  Sent "progress tracking" e-mail.
  Began commenting genetic algorithm functions, pushing notebook start until tomorrow. Would like to to a descriptive written background of project in that notebook.

#Tuesday December 18th
1. Continue commenting some of GA functions
2. Write and apply description of project in GA notebook
3. Organize code in GA notebook
4. Add descriptions and walk-through in GA notebook



