---
title: "ToDo's and Progress Tracking Notebook"
output: pdf_document
---

This notebook is intended to keep track of my progress each day over intercession on this project. I'll log my TODO's each morning or night and what I've accomplished each day. Let's hope I keep up with it properly.

#Monday December 17th
###TO DO
1. Re-arrange Github repos
2. Organize Google Drive papers & PDF's
3. Print most useful papers
4. Send "progress tracking" e-mail to Seid & Graham
5. Compile genetic algorithm functions into notebook
  + Comment genetic algorithm code

###Progress

Github repositories organized, took far longer than I thought it would. I learned he significance of .git files after attempting to create new repos out of existing but removed repo folders with .git files in them.  
Organized Google Drive folders & papers, selected those to print.  
Sent "progress tracking" e-mail.  
Began commenting genetic algorithm functions, pushing notebook start until tomorrow. Would like to to a descriptive written background of project in that notebook.  

#Tuesday December 18th
###TO DO
1. Continue commenting some of GA functions
2. Write and apply description of project in GA notebook
3. Organize code in GA notebook
4. Add descriptions and walk-through in GA notebook
  + Add section describing species and population creation

###Progress
Major progress on today's todos. If not finished, each point is nearly completed.  
GA notebook still needs work in analyzing finals plots.  
GA functions could use some better commenting.  

#Wednesday December 19th
###TO DO
Today's ToDo: (Technical, "Figure-Stuff-Out" Day)

1. Look into setting up RStudio Server on Linux Lab PC
2. Create package for GA functions as practice
  
Carried over from Yesterday:

1. Continue GA notebook, analyze advanced plots.
2. Continue GA function commenting, possibly re-organize functions?
  
Looking Forward / Rolling ToDo:

1. Make larger plan for going forward
2. Compile plan into a chart / pseudocode
3. Look more into literature: how to apply GA to this project

###Progress
I spent a good amount of time fiddling with RStudio Server on the CAELinux PC in the lab without any luck in accessing it from another computer. Judging by some similar problems on discussion forums, it seems like the school networking is blocking the PC from opening the correct ports to access it remotely.   
Then I moved on to compiling my GA functions into a package, which was successful but I ahve not uploaded it to CRAN.   
Lastly, I made major progress on the GA notebook. All that is left to do is explore a frew more functions for the contour plots in order to better understand the evolution process in these algorithms.

#Thursday December 20th
###TO DO
Today's ToDo: (Big Picture Day)

1. Finalize GA notebook.
2. See "looking forward", make plans for work during/after break.
3. Review "Math Framework for Task Reportoire Expansion" paper and decide if that model fits.
  
Looking Forward / Rolling ToDo:

1. Make larger plan for going forward as chart / pseudocode
2. Look more into literature: how to apply GA to this project, [Annotated Bibliography Google Doc]("https://docs.google.com/document/d/1Eu_zMDIhtgkyTLazfbn7v8vJ5Pa9T_E6ZIkz92yFPWk/edit?usp=sharing")

###Progress
After reading some literature, I wrote "ThresholdNotebook" to better understand the claims of a paper on the robustness of a colony with greater genetic variability. This notebook outlines the exact simulation of the paper. While this simulation was very simple, I would like to continue investigating the idea of genetic variability and robustness to a changing environment and task demands.
Need to keep looking into literature and frame research question properly.

#Friday December 21st - Tuesday January 1st
Took Holiday Break

#Wednesday January 2nd - Friday January 4th
Wisdom Teeth Removed, out of commission for a few days.

#Saturday January 5th
Back to work.  

###TO DO
Today's ToDo:
1. Work on ThresholdNotebook, see if I can draw any further conclusions on the work than the authors did.

Rolling ToDo:
1. Make larger plan for going forward as flowchart / pseudocode
2. Look more into literature: how to apply GA to this project, [Annotated Bibliography Google Doc]("https://docs.google.com/document/d/1Eu_zMDIhtgkyTLazfbn7v8vJ5Pa9T_E6ZIkz92yFPWk/edit?usp=sharing"). Specifically, review "Math Framework for Task Reportoire Expansion" paper and decide if that model fits.









